### ISSUE TITLE
Unable to find location

### ISSUE THREAD

**Issue by ghsttwn** [casasfernando/wingpanel-indicator-weather#2]
The indicator refuses to show the weather. I've tried re-installing but it is still the same.

Also, changes to settings won't be reflected. I can't even change the location. If I choose a random location from the search bar it does nothing, so the "Location discovery" switch.

![image](https://user-images.githubusercontent.com/86124825/132627016-0fd42693-8b2e-459d-886a-4904b90b0062.png)

**Comment by casasfernando** [comment]
Which version of elementary OS are you using? In Odin it seems there is a problem with geoclue that is preventing location discovery to work as expected. Not sure if it’s solved I will check again.

Now regarding manual location search:

- The indicator use libgweather and it’s location database. If the location you are searching for is not available there you can reported it to libgweather so it can be added. More information: https://wiki.gnome.org/Projects/LibGWeather/ImprovingLocations
- If the location is available in libgweather another reason to not get weather data is that the weather service itself doesn’t provide data for that location. If you want to share a location example I can try to repro or you may want to try with a well known location (eg: big city like a country capital) and see if you get information for that.

Thanks.

**Comment by casasfernando** [comment]
The issue in Odin with geoclue is still open: https://github.com/elementary/pantheon-agent-geoclue2/issues/41

So for now in Odin "Location discovery" will not work.
I will add a notice in the README file for awareness.

**Comment by casasfernando** [comment]
So @ghsttwn I tried to repro your problem but I didn't succeed.
I tried to manually search and select different major cities across the world and for all of them I was able to get weather information:

- New York city (US)
- Toronto (Canada)
- Buenos Aires (Argentina)
- London (UK)
- Rosario (Argentina)
- Santiago (Chile)

Another interesting thing I found is that turning on "Location discovery" actually works for me now (I tought it was broken in Odin, and for sure it was not working some time ago). So I will amend my comments above.

- Can you share with me examples of location that doesn't work for you when using the manual search?
- When you manually search for a location: how are you selecting it? Clicking on it in the search results list?

Thanks.

**Comment by ghsttwn** [comment]
Okay, after re-installing yet again it started working. I'm not really sure why did it happen in the first place, but I think I lost internet connection and then it happened.

**Comment by ghsttwn** [comment]
> Can you share with me examples of location that doesn't work for you when using the manual search?

I started looking for cities like New York and Ciudad de México but when choosing one of them it'll go back to the city I already had.
 
> When you manually search for a location: how are you selecting it? Clicking on it in the search results list?

I tried clicking it directly and pressing Enter. No luck.

These do not apply to me anymore, but I'm pretty sure it'll eventually happen again. I have a very unstable internet connection so... 😬

**Comment by casasfernando** [comment]
This is expected.
If there is no Internet connection and the indicator fails to retrieve weather data then "N/A" is displayed since data is not available.
Also if this happens while changing the location, the location change will rollback to the previous "known to work" one.

Feel free to reach out again if you find any other issues.

Thanks
