### ISSUE TITLE
Weather is N/A

### ISSUE THREAD

**Issue by pckotzer** [casasfernando/wingpanel-indicator-weather#9]
After upgrade to 23.04 from ubuntu 22.04 it shows only N/A in weather, no matter what location i select.
I use elementary os 7

**Comment by casasfernando** [comment]
elementary OS 7.1 is still based on Ubuntu 22.04 so maybe you are in an unsupported scenario.
Please share the output of the following commands:

1. `cat /etc/os-release`
2. `apt list --installed | grep weather`

Thanks

**Comment by pckotzer** [comment]
I tried today the .deb and it works after a reboot. Dont know what the problem was, but i think i missed the weather packages. I did a manual upgrade by going from "focal to "lunar" in source.list in /etc/apt and back then it stoped working and i decided to build from source and got many dependencie error's that i fixed with aptitude back then. Now after some month i tried the .deb it just worked after a reboot. Thought it will work never again haha. Thanks for this great indicator for wingpanel!
